const SET_MAIN_STREAM = "SET_MAIN_STREAM";
const ADD_PARTICIPANT = "ADD_PARTICIPANT";
const REMOVE_PARTICIPANT = "REMOVE_PARTICIPANT";
const SET_USER = "SET_USER";
const UPDATE_USER = "UPDATE_USER";
const UPDATE_PARTICIPANT = "UPDATE_PARTICIPANT";

export {
    SET_MAIN_STREAM,
    ADD_PARTICIPANT,
    REMOVE_PARTICIPANT,
    SET_USER,
    UPDATE_USER,
    UPDATE_PARTICIPANT
}